# Generated by Django 5.1.2 on 2024-10-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multishop', '0007_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
